    <!-- Favicon -->
    <link rel="icon" href="assets/img/Favicon-transparent.svg">
    <!-- Fonts -->
    <link rel="stylesheet" href="https://use.typekit.net/zvm6eqf.css">
    <!-- Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <!-- Tailwind -->
    <link rel="stylesheet" href="dist/css/styles.css">
    <!-- CSS -->
    <link rel="stylesheet" href="assets/css/main.css">
    <!-- JS -->
    <script src="assets/js/menu.js" defer></script>
    <script src="assets/js/foods.js" defer></script>
